const token =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMiwic29sdXRpb24iOiIwMTAwMTExMDAxMDAwMTAwMDEwMDAxMDEwMDExMDAxMTAxMDAxMTAxMDExMDEwMTAwMTAxMTAwMTAwMTEwMTAxMDEwMDExMTAwMTExMTAxMDAxMDAxMDAxMDAxMTAwMTAwMTAwMTExMDAxMDEwMTAwMDEwMDEwMDEwMTExMDExMTAxMDAxMTEwMDExMTEwMTAwMTAxMDAwMTAwMTEwMDEwMDEwMDExMDEwMTEwMTAxMDAxMDExMDAxMDExMTEwMDAwMTAwMTExMDAxMTAxMDEwMDEwMDAxMDEwMDExMDAxMDAxMDExMDEwMDEwMTAxMDAwMTAwMTAwMTAxMTEwMTExMDEwMDExMTAwMTExMTAxMDAxMDEwMDAxMDAxMTAwMTEwMTAwMTExMDAxMTAxMDEwMDEwMTEwMDEwMDExMDEwMTAxMDAxMTEwMDExMTEwMTAwMTAwMTAwMTAxMTExMDAxMDEwMDExMDEwMTAwMDEwMDAxMDExMDEwMDExMDEwMTAwMTAwMTExMDAxMTAxMDEwMDEwMDEwMDEwMDExMDAxMDAxMDAxMTExMDEwMDAxMDAwMTAwMTAwMTAxMTEwMTExMDEwMDExMTAwMTEwMTAxMDAxMTAwMTExMDAxMTAwMTAwMTAwMTEwMTAxMTExMDEwMDEwMDEwMTAwMTEwMTEwMDAxMDAxMTAxMDExMDEwMTAwMTAwMDAwMTAwMTEwMDAwMDEwMDExMDEwMTAxMDEwMDAxMTAwMDExMDExMTEwMDEwMTAwMTExMDAxMTAxMDEwMDExMDEwMTEwMDExMDAxMTAxMDAxMTAxMDExMDEwMTAwMTAxMTAwMTAwMTEwMDAxMDEwMDExMDEwMTEwMTAxMDAxMDAwMDAxMDAxMTAwMTEwMTAwMTExMDAxMDAwMTAwMDEwMTEwMDEwMTExMTAwMTAxMDAxMTEwMDExMDEwMTAwMTAwMDEwMTAwMTEwMDEwMDEwMDExMDEwMTAxMDEwMDAxMDExMDEwMDExMDExMDAwMTAwMTEwMTAxMTAxMDEwMDEwMDAwMDEwMDExMDAxMTAxMDAxMTExMDEwMTAxMDAwMTEwMDAxMTAxMTExMDAxMDEwMDExMTAwMTEwMTAxMDAxMTAwMDExMDExMTEwMDEwMTAwMTEwMTAxMDAwMTAwMDEwMTEwMTAwMTEwMTAxMDAxMDAxMTEwMDExMDEwMTAwMTAwMTAwMTAwMTEwMDEwMDEwMDExMTEwMTAwMDEwMDAxMDAxMDAxMDExMTAxMTEwMTAwMTExMDAxMTExMDEwMDEwMDAxMDEwMDExMDAxMDAxMDAxMTAxMDExMDEwMTAwMTAxMTAxMDAxMTAxMDAwMDEwMDExMTAwMTEwMTAxMDAxMDAwMTAxMDExMTEwMDEwMTAxMTAxMDAxMDEwMTAwMDEwMDEwMDEwMTExMDExMTAxMDAxMTEwMDEwMDAxMDAwMTEwMDAxMTAwMTEwMDExMDEwMDExMTAwMTAxMDEwMDAxMTAwMDExMDExMTEwMDEwMTAwMTEwMTAxMTAxMDEwMDEwMDAwMDEwMDExMDAxMDAxMDAxMTEwMDExMDEwMTAwMTAxMTAwMTAxMTExMDAxMDEwMDExMTAwMTExMTAxMDAxMTAxMDExMDAxMTAwMTAwMTAwMTExMTAxMDAwMTAwMDEwMTEwMDEwMDExMDAxMTAxMDAxMTEwMDExMTEwMTAwMTAxMTAwMTAwMTEwMDEwMDEwMDExMDEwMTEwMTAxMDAxMDExMDAxMDExMTEwMDAwMTAwMTEwMTAxMTAxMDEwMDEwMDAwMDEwMDExMDAxMTAxMDAxMTEwMDExMDEwMTAwMTAxMTAwMTAwMTEwMDEwMDEwMDExMDEwMDExMDAxMDAxMDAwMTAxMDExMTEwMDEwMTAwMTEwMTAxMDAwMTAwMDEwMDEwMDEwMTExMTAwMTAxMDAxMTEwMDEwMTAxMDAwMTAwMTAwMTAwMTEwMDEwMDEwMDExMDEwMTAxMDEwMDAxMTAwMDExMDExMTAxMTEwMTAwMTExMDAxMTAxMDEwMDEwMDEwMDEwMDExMDAxMTAxMDAxMTAxMDEwMTAxMDAwMTEwMDAxMTAwMTEwMDEwMDEwMDExMTAwMTEwMTAxMDAxMDAwMTAxMDAxMTAwMTEwMTAwMTExMDAxMDAwMTAwMDEwMDEwMDEwMTExMDExMTAxMDAxMTEwMDEwMTAxMDAwMTAxMDEwMTAwMTEwMDExMDEwMDExMDEwMTEwMTAxMDAxMTAwMDExMDAxMTAxMDEwMTAwMTExMDAxMTExMDEwMDExMDEwMTEwMTExMTAwMTAxMDAxMTAxMDExMDAxMTEwMDExMTEwMTAwMTExMTAxIn0.qdZUk6Oxr63WZ5_7owo3cZMLSN6tYvOFl3n3ROVLqQg";
const tokenExample = `${token.substring(0, 50)}...${token.substring(
  token.length - 10,
)}`;

export const AUTH_SWAGGER = {
  fields: {
    accessToken: {
      description: "JWT access token",
      example: tokenExample,
      format: "jwt",
    },

    clearRefreshToken: {
      description: "Clear refresh token cookie",
      schema: {
        example:
          "refresh_token=; Path=/auth; Expires=Thu, 01 Jan 1970 00:00:00 GMT",
        type: "string",
      },
    },

    refreshToken: {
      description: "JWT refresh token (HttpOnly cookie)",
      schema: {
        example: `${tokenExample}; HttpOnly; Secure; SameSite=Strict`,
        format: "jwt",
      },
    },
  },

  responses: {
    login: {
      OK: "Authenticate user and return access token. Refresh token is set via HttpOnly cookie.",
      UNAUTHORIZED: "Invalid username or password",
    },

    logout: {
      OK: "Logout user and clear refresh token cookie.",
    },

    me: {
      OK: "Return authenticated user",
      UNAUTHORIZED: "Unauthorized",
    },

    refresh: {
      OK: "Issue a new access token and rotate refresh token. New refresh token is set via HttpOnly cookie.",
      UNAUTHORIZED: "Invalid or expired refresh token",
    },
  },
};
